server:
  port: ${PORT:8081}
  servlet:
    context-path: /api

spring:
  application:
    name: proposta
  profiles:
    active: ${PROFILE:dev}
  jackson:
    serialization:
      write_dates_as_timestamps: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      database-plataform: org.hibernate.dialect.H2Dialect
      naming-strategy: org.hibernatge.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      open-in-view: false

  datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:proposta
      username: root
      password: root
      testWhileIdle: true
      validationQuery: Select 1
      platform: h2-dev
      initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: full
        errorDecoder: com.zup.academy.proxies.config.ClientErrorDecoder

  metrics:
    enabled: true

keycloak:
  keyfactory: "RSA"
  configurationFile: "classpath:keycloak.json"

opentracing:
  jaeger:
    enabled: true
    service-name: "proposta"
    http-sender:
      url: ${JAEGER_ENDPOINT:http://localhost:14268/api/traces}
    probabilistic-sampler:
      sampling-rate: 1
  spring:
    cloud:
      feign:
        enabled: false

clients:
  contas:
    url: ${URL_SISTEMA_CARTAO:localhost:8888/api/cartoes}
  analise:
    url: ${URL_SISTEMA_CONTAS:localhost:9999/api}

management:
  endpoints:
    web:
      exposure:
        include: '*'
    metrics:
      export:
        prometheus:
          enabled: true
    endpoint:
      metrics:
        enabled: false
      prometheus:
        enabled: true
