server:
  port: 8081
  servlet:
    context-path: /proposta

spring:
  application:
    name: proposta
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      database-plataform: org.hibernate.dialect.H2Dialect
      naming-strategy: org.hibernatge.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      open-in-view: false

  datasource:
    driverClassName: org.h2.Driver
      url: jdbc:h2:mem:proposta
      username: root
      password: root
      testWhileIdle: true
      validationQuery: Select 1
      platform: h2-dev
      initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console