server:
  port: ${PORT:8081}
  servlet:
    context-path: /propostas

spring:
  application:
    name: proposta
  profiles:
    active: ${PROFILE:dev}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      database-plataform: org.hibernate.dialect.H2Dialect
      naming-strategy: org.hibernatge.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      open-in-view: false

  datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:proposta
      username: root
      password: root
      testWhileIdle: true
      validationQuery: Select 1
      platform: h2-dev
      initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

feign:
  client:
    config:
      default:
        errorDecoder: com.zup.academy.proxies.config.ClientErrorDecoder
  metrics:
    enabled: true

keycloak:
  keyfactory: "RSA"
  configurationFile: "classpath:keycloak.json"

opentracing:
  jaeger:
    enabled: true
    service-name: "proposta"
    http-sender:
      url: ${HOST_OPEN_TRACING:http://localhost:14268/api/traces}
    probabilistic-sampler:
      sampling-rate: 1
  spring:
    cloud:
      feign:
        enabled: false

clients:
  account:
    url: ${ACCOUNT_HOST:localhost:8888/api/cartoes}
  solicitacao:
    url: ${SOLICITACAO_HOST:localhost:9999/api}
